model_list:
  # - model_name: gpt-4o
  #   litellm_params:
  #     model: openai/gpt-4o
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
  # - modal_name: claude-3-7-sonnet
  #   litellm_params:
  #     modal: anthropic/claude-3-7-sonnet-20250219
  - model_name: DeepSeek V3
    litellm_params:
      model: deepseek/deepseek-chat
  - model_name: DeepSeek R1
    litellm_params:
      model: deepseek/deepseek-reasoner
  # - model_name: gemini-1.5-pro-latest
  #   litellm_params:
  #     model: gemini/gemini-1.5-pro-latest
  #     safety_settings:
  #       - category: HARM_CATEGORY_HARASSMENT
  #         threshold: BLOCK_NONE
  #       - category: HARM_CATEGORY_HATE_SPEECH
  #         threshold: BLOCK_NONE
  #       - category: HARM_CATEGORY_SEXUALLY_EXPLICIT
  #         threshold: BLOCK_NONE
  #       - category: HARM_CATEGORY_DANGEROUS_CONTENT
  #         threshold: BLOCK_NONE
  # - model_name: pplx-llama-3.1-sonar-huge
  #   litellm_params:
  #     model: perplexity/llama-3.1-sonar-huge-128k-online
