model_list:
  - model_name: gpt-4o
    litellm_params:
      model: openai/gpt-4o
  - model_name: claude-3-5-sonnet
    litellm_params:
      model: anthropic/claude-3-5-sonnet-20240620
  - model_name: claude-3-7-sonnet-20250219
    litellm_params:
      model: anthropic/claude-3-7-sonnet-20250219
      api_key: os.environ/ANTHROPIC_API_KEY
      thinking: { "type": "enabled", "budget_tokens": 1024 }
  - model_name: DeepSeek V3
    litellm_params:
      model: deepseek/deepseek-chat
  - model_name: DeepSeek R1
    litellm_params:
      model: deepseek/deepseek-reasoner
